FROM python:3.7
MAINTAINER Vladyslav_Tkachuk3@epam.com

WORKDIR APP

RUN apt-get update && apt-get install make

RUN pip install --upgrade pip && pip install -r requirements.txt 

EXPOSE 80 

CMD ["python", "app.py"]
